site_name: motor_odm
site_description: pyhthon async mongodb ODM using motor and pydantic
site_url: https://github.com/ramzitannous/Motor_ODM

theme:
    name: 'material'

repo_name: ramzitannous/Motor_ODM
repo_url: https://github.com/ramzitannous/Motor_ODM
edit_uri: ''

nav:
    - motor_odm: 'index.md'
